[package]
name = "wasmer_ex"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "wasmer_ex"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.36.1"
rand = "0.9.1"
sha2 = "0.10.8"
wasmer = "5.0.4"
wasmer-compiler-singlepass = "5.0.4"
wasmer-middlewares = "5.0.4"
rocksdb = { git = "https://github.com/rust-rocksdb/rust-rocksdb", branch = "master" }
lazy_static = "1.4.0"
